site_name: Tercen Starter Guide
docs_dir: docs/
site_url: "https://tercen.com"
repo_url: https://github.com/tercen/starter_guide
repo_name: tercen/starter_guide
edit_uri: edit/main/docs/
site_author: Tercen Authors
site_description: "Tercen Get Started Guide"
use_directory_urls: true

copyright: Copyright &copy; 2024 Tercen

theme:
  name: material
  # custom_dir: .docs/overrides/
  font: false
  favicon: https://tercen.com/_assets/brand/fav.png
  logo: ./images/tercen-logo-sq.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - instant
    - navigation.footer
    - navigation.path
    - navigation.sections
    #    - navigation.expand
    - navigation.tabs
    #    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tabs
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
extra_css:
  - stylesheets/style.css
plugins:
  - search
  - git-committers:
      repository: tercen/starter_guide
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  #  - exclude:
  #      glob:
  #        - README.md
  #        - "*.gotmpl"
  #        - "*.gotmpl.md"
  #  - awesome-pages
  # - macros:
  #     module_name: .docs/macros/includes/main
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  # - redirects:
  #     redirect_maps:
  #       README.md: Getting-Started/intro.md
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true # set to false to leave out the version selector
      css_dir: css # the directory to put the version selector's CSS
      javascript_dir: js # the directory to put the version selector's JS
      canonical_version:
        null # the version for <link rel="canonical">; `null`
      # uses the version specified via `mike deploy`
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
extra:
  version:
    provider: mike

nav:
  - Introduction: index.md
  - Tutorial:
      - Create a Project: create_a_project.md
      - Upload Data: upload_data.md
      - Basic Analysis - Workflow: workflow.md
      - Using Operators: operators.md
      - Join Data files: join.md
      - Export a Data Table: export_data.md
      - Perform a Gather: gather.md
      - Apply a Filter: filter.md
      - Collaboration Tips: collaborate.md
